/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views.estudiantes;
import models.Alumnos;
import SQL.AlumnosSQL;
import javax.swing.JOptionPane;
import models.RandomPassword;
import models.hash;

/**
 *
 * @author Luis
 */
public class Insert_Alumno extends javax.swing.JFrame {
    
    String randomPass = RandomPassword.generateRandomPassword(5);
    /**
     * Creates new form Insert_Alumno
     */
    public Insert_Alumno() {
        initComponents();
        setLocationRelativeTo(null);
    }
    //metodo para extraer datos de los textfield
    public Alumnos sendFormulario(){
        //Instanciar el objeto
        Alumnos alumno = null;
        try {
        String usuario, nombre, apellido, direccion, telefono ,correo;
        usuario = t_usuario.getText();
        nombre = t_nombre.getText();
        apellido = t_apellido.getText();
        direccion = t_direccion.getText();
        telefono = t_telefono.getText();
        correo = t_correo.getText();
        int rol = 1;
        int edad = Integer.parseInt(t_edad.getText());
        alumno = new Alumnos(usuario, randomPass, nombre, apellido, direccion, telefono, correo, edad, rol);
        } catch (Exception e) {
            e.printStackTrace(System.out);
        }
        return alumno;
        //System.out.println("Contraseña aleatoria: "+ randomPass + " contraseña encriptada: "+ contraEncriptada);
    }
    void limpiar(){
        t_usuario.setText("");
        t_nombre.setText("");
        t_apellido.setText("");
        t_direccion.setText("");
        t_telefono.setText("");
        t_correo.setText("");
        t_edad.setText("");
    }
    boolean validaciones(){
        boolean isValid = true;
        if(!!t_usuario.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Usuario vacio, complete los datos");
            return !isValid;
        }
        if(!!t_nombre.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Nombre vacio, complete los datos");
            return !isValid;
        }
        if(!!t_apellido.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Apellido vacio, complete los datos");
            return !isValid;
        }
        if(!!t_direccion.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "La direccion esta vacia, complete los datos");
            return !isValid;
        }
        if(!!t_telefono.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Telefono vacio, complete los datos");
            return !isValid;
        }
        if(!!t_edad.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Edad vacia, complete los datos");
            return !isValid;
        }
        if(!!t_correo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Correo vacio, complete los datos");
            return !isValid;
        }
        return isValid;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        t_usuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        t_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        t_apellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        t_direccion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        t_telefono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        t_edad = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        t_correo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btn_registrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Usuario:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));
        jPanel1.add(t_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 150, -1));

        jLabel2.setText("nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, -1, -1));
        jPanel1.add(t_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 150, -1));

        jLabel3.setText("Usuario:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 150, -1));
        jPanel1.add(t_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 150, -1));

        jLabel4.setText("apellido:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));
        jPanel1.add(t_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 150, -1));

        jLabel5.setText("Direccion:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));
        jPanel1.add(t_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 150, -1));

        jLabel6.setText("Telefono:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));
        jPanel1.add(t_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 150, -1));

        jLabel7.setText("Edad:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));
        jPanel1.add(t_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 150, -1));

        jLabel8.setText("Correo:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        btn_registrar.setText("Registar Alumno");
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
        AlumnosSQL sql = new AlumnosSQL();
       if(!validaciones()){
           return;
       }
       int respuesta = sql.createAlumno(sendFormulario());
       if(respuesta == 0){
       JOptionPane.showMessageDialog(null, "No se pudo registrar el alumno");
            limpiar();
            return;
        }
        JOptionPane.showMessageDialog(null, "Alumno Registrado");
        JOptionPane.showMessageDialog(null, "La contraseña temporal es: "+randomPass);
        limpiar();

    }//GEN-LAST:event_btn_registrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Insert_Alumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Insert_Alumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Insert_Alumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Insert_Alumno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Insert_Alumno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_registrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField t_apellido;
    private javax.swing.JTextField t_correo;
    private javax.swing.JTextField t_direccion;
    private javax.swing.JTextField t_edad;
    private javax.swing.JTextField t_nombre;
    private javax.swing.JTextField t_telefono;
    private javax.swing.JTextField t_usuario;
    // End of variables declaration//GEN-END:variables
}
